### ISSUE TITLE
我如何使用并验证效果？希望能出个安装运行示例，感谢

### ISSUE THREAD

**Issue by LuckyIvan** [IDKiro/sdxs#12]
是否支持cenos下安装等，最近也在做生图加速的工作，希望能有收获

**Comment by IDKiro** [comment]
centos？没有验证过，搞CV任务一般都用ubuntu。
如果你没有相关经验，建议先去diffusers库看一下，那边有基础的用例：
https://github.com/huggingface/diffusers

**Comment by IDKiro** [comment]
Re-open if necessary
