### ISSUE TITLE
SSIM parameter

### ISSUE THREAD

**Issue by trungdt880** [IDKiro/sdxs#14]
Hi, very interesting work indeed. I was wondering, how did you pick the parameter for the SSIM loss since you're using it in the latent space, specifically the data_range and the window_size. Looking forward to your answer, thank you!!

**Comment by IDKiro** [comment]
Instead of setting the window size, we directly calculate the full feature maps' mean, variance and covariance. You can use DISTS loss directly, and in our experiments the difference between the two is not significant, especially since we turn down the weights for feature matching later in the training.

**Comment by trungh2corp** [comment]
Thank you for the rapid response, much appreciated!
I see, so in case of SSIM, the data range is calculated dynamically base on each input?
I've tried DISTS loss beforehand and it works quite well, hoơever your application of SSIM is quite interesting too so I would like to test it out💪💪

**Comment by trungdt880** [comment]
Thank you for the rapid response, much appreciated!
I see, so in case of SSIM, the data range (which is used to calculate $C_1,C_2$ is calculated dynamically base on each input?
I've tried DISTS loss beforehand and it works quite well, however your application of SSIM is quite interesting too so I would like to test it out💪💪

**Comment by IDKiro** [comment]
Yes, we are using the original SSIM formula directly:
$$\text{SSIM}(\mathbf{x},\mathbf{y})=\frac{(2\mu_x\mu_y+C_1)(2\sigma_{xy}+C_2)}{(\mu_x^2+\mu_y^2+C_1)(\sigma_x^2+\sigma_y^2+C_2)}$$

**Comment by trungdt880** [comment]
I see, thanks again 💪
