### ISSUE TITLE
SDXS-512 1.0 release

### ISSUE THREAD

**Issue by rupeshs** [IDKiro/sdxs#4]
Nice work, any plan for the SDXS-512 1.0 release?
Thanks.

**Comment by IDKiro** [comment]
If I obtain permission from the company, I think this will happen within a month.

**Comment by rupeshs** [comment]
@IDKiro thank you

**Comment by IDKiro** [comment]
SDXS-512-DreamShaper is released. It is similar in quality to 1.0. I would like to contribute more to the community, but that might conflict with company business. This version is trained separately for open source, so I hope you can understand that.

**Comment by rupeshs** [comment]
@IDKiro  Thanks for the update

**Comment by IDKiro** [comment]
The subsequent open source program has been terminated by the Company. I'll reopen these issues if there are subsequent progress.
