### ISSUE TITLE
inpaint model release

### ISSUE THREAD

**Issue by Decem-Y** [IDKiro/sdxs#5]
Would you consider releasing an inpaint model?

**Comment by IDKiro** [comment]
This is a good idea, and I will add it to my to-do list. However, due to our manpower shortage (only me focusing on SDXS), it might start after a month.

**Comment by Decem-Y** [comment]
> This is a good idea, and I will add it to my to-do list. However, due to our manpower shortage (only me focusing on SDXS), it might start after a month.

This is awesome, looking forward to your future work.

**Comment by garbe-github-support** [comment]
great work！

**Comment by IDKiro** [comment]
The subsequent open source program has been terminated by the Company. I'll reopen these issues if there are subsequent progress.
