### ISSUE TITLE
How to access the prompt of Laion-5b?

### ISSUE THREAD

**Issue by Luo-Yihong** [IDKiro/sdxs#9]
Thanks for your impressive work! I found that you use the prompt of Laion-5B to generate data, can you share the way to access the prompt of Laion-5B?

**Comment by IDKiro** [comment]
Yes, LAION-5B is now closed for download and our dataset was downloaded before it was closed. 
You can try this:
https://huggingface.co/datasets/guangyil/laion-coco-aesthetic
I am now using the CAPTION item from this dataset for training.

**Comment by Luo-Yihong** [comment]
> Yes, LAION-5B is now closed for download and our dataset was downloaded before it was closed. You can try this: https://huggingface.co/datasets/guangyil/laion-coco-aesthetic I am now using the CAPTION item from this dataset for training.

Thank you for your help! That is super nice for me!
